[package]
name = "gdrust-sprite3d-angle-animator"
version = "0.1.0"
edition = "2021"
authors = ["Jason.json"]

[dependencies]
sided-animation-derive = { path = "./sided-animation-derive" }
animation-core = { path = "./animation-core" }
